
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 1234
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: mjhr3_development

test:
  <<: *default
  database: mjhr3_test

production:
  <<: *default
  database: mjhr3_production
  username: mjhr3
  password: <%= ENV['MJHR2_DATABASE_PASSWORD'] %>
